#spring.application.name=hello-client-res
#
#server.port=8888

server:
 port: 8888
 
resilience4j:
 circuitbreaker:
   instances:
     clientService:
      registerHealthIndicator: true
      eventConsumerBufferSize: 10
      automaticTransitionFromOpenToHalfOpenEnabled: true
      failureRateThreshold: 50
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowSize: 10
      waitDurationInOpenState: 5s
      slidingWindowType: COUNT_BASED

spring:
  application:
    name: hello-srvice-res4j-client   
   
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
   health:
     show-details: always
